### ISSUE TITLE
App not rendering Donut and Pie charts 

### ISSUE THREAD

**Issue by deisi** [flathub/info.portfolio_performance.PortfolioPerformance#16]
Only after an initial restart, the app renders donuts and pie charts correctly.
https://forum.portfolio-performance.info/t/pie-and-donut-charts-not-rendering/16435/7

The bare binary suffers from the same.

More discussion:
https://forum.portfolio-performance.info/t/keine-tortendiagramme-sichtbar/370/61

**Comment by buchen** [comment]
I propose to close this issue. With the December 2022 version, there is an alternative implementation that uses SWT natively (instead of using an embedded browser). It comes with its own drawbacks (slices below 1 degree), but at least the diagrams are functional. The SWT-based diagrams should be enable on Linux by default
