### ISSUE TITLE
question on dependencies Fedora - org.freedesktop.Platform.GL.default

### ISSUE THREAD

**Issue by donvipre** [flathub/info.portfolio_performance.PortfolioPerformance#90]
Hi,

I wonder where the package dependencies are defined for the flatpak.

I recently updated my hard drive and used this to clean up my system as well, meaning installing Fedora 38 from scratch and also all the flatpaks I am using.

I started with Signal (`flatpak install flathub org.signal.Signal`) delivering the following changes:
```shell
        ID                                               Branch                 Op            Remote             Download
 1. [✓] org.freedesktop.Platform.GL.default              23.08                  i             flathub            158,8 MB / 159,1 MB
 2. [✓] org.freedesktop.Platform.GL.default              23.08-extra            i             flathub             16,2 MB / 159,1 MB
 3. [✓] org.freedesktop.Platform.Locale                  23.08                  i             flathub             24,1 MB / 355,5 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel             23.08                  i             flathub             13,3 MB / 13,4 MB
 5. [✓] org.freedesktop.Platform.openh264                2.2.0                  i             flathub            887,4 kB / 944,3 kB
 6. [✓] org.freedesktop.Platform                         23.08                  i             flathub            174,4 MB / 224,1 MB
 7. [✓] org.signal.Signal                                stable                 i             flathub            149,3 MB / 155,3 MB
```

then I went on with `flatpak install flathub info.portfolio_performance.PortfolioPerformance` delivering the following packages:

```shell
        ID                                                           Branch                   Op             Remote              Download
 1. [✓] org.freedesktop.Platform.GL.default                          22.08                    i              flathub             142,8 MB / 143,1 MB
 2. [✓] org.freedesktop.Platform.GL.default                          22.08-extra              i              flathub              16,3 MB / 143,1 MB
 3. [✓] org.freedesktop.Platform.VAAPI.Intel                         22.08                    i              flathub              13,3 MB / 13,4 MB
 4. [✓] org.gnome.Platform.Locale                                    44                       i              flathub               1,7 MB / 340,6 MB
 5. [✓] org.gnome.Platform                                           44                       i              flathub             265,5 MB / 326,8 MB
 6. [✓] info.portfolio_performance.PortfolioPerformance              stable                   i              flathub             137,1 MB / 118,5 MB
```

Where do I find the dependency to 22.08 instead of 23.08?

Best regards,
Uwe Arnold

**Comment by roshanshariff** [comment]
We depend on org.gnome.Platform version 44, which in turn depends on org.freedesktop.Platform 22.08. The Gnome 45 platform would depend on 23.08 (compare [44](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/gnome-44/elements/freedesktop-sdk.bst?ref_type=heads) vs [45](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/gnome-45/elements/freedesktop-sdk.bst?ref_type=heads)).

Since Portfolio Performance is based on the Eclipse platform, we try to track the version of Gnome used by the [Eclipse Flatpak](https://github.com/flathub/org.eclipse.Javascript/blob/d5e293d15ba35924213aec861f689961c195f1ea/org.eclipse.Javascript.json#L4). We don't use the latest available version of Gnome because it takes some time for compatibility issues with the Eclipse platform to be resolved; we've had more luck using the previous version (which is still supported).

**Comment by donvipre** [comment]
@roshanshariff : thank you for the information.
